# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  canary-percentage:
    description: 'percentage of traffic to send to canary'
    required: true
    default: '0'
  main-percentage:
    description: 'percentage of traffic to send to canary'
    required: true
    default: '100'
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs. }}